### ISSUE TITLE
GSEA has ties in the preranked stats

### ISSUE THREAD

**Issue by rysterzhu** [YuLab-SMU/clusterProfiler#214]
some genes have the same rank Foldchange.It's not a warnning but an error.How skip it

GSEA(cdata3, exponent = 1, nPerm = 1000, minGSSize = 10,
+   maxGSSize = 1000, pvalueCutoff = 0.05, pAdjustMethod = "BH",
+   TERM2GENE = gmt,
+   by = "fgsea")

preparing geneSet collections...
GSEA analysis...
There are ties in the preranked stats (5.39% of the list).
The order of those tied genes will be arbitrary, which may produce unexpected results.
Error in if (maxP > -minP) { : missing value where TRUE/FALSE needed

**Comment by ashakru** [comment]
It means that there are genes in your preranked list having the same numerical/ranking value. For example, if you rank genes by log2 fold change, genes with the same log2 fold change value will be ordered randomly once processed. You can use `rank()` function and a `ties.method` parameter to control how genes with the same value are ranked: 
```
> head(genesTables)
  entrezgene_id log2FoldChange  rank
1         11122       2.299289 10229
2          8618       1.842938 10228
3          6776       1.822533 10227
4          9586       1.815413 10226
5         79047       1.643554 10225
6          8739       1.621242 10224
> 
> genesTables <- genesTables %>%
+   mutate(rank = rank(log2FoldChange,  ties.method = "random")) 
> 
> head(genesTables)
  entrezgene_id log2FoldChange  rank
1         11122       2.299289 10229
2          8618       1.842938 10228
3          6776       1.822533 10227
4          9586       1.815413 10226
5         79047       1.643554 10225
6          8739       1.621242 10224
```

**Comment by elfore** [comment]
@ashakru 
I am afraid I might need to reopen this issue due to the similar problem recently.

gene_list is a gene list expression vector with entrizid as name, if I sort it then run gseaKEGG
```R
gene_list = sort(gene_list, decreasing = T)
e_kegg = gseKEGG(geneList     = gene_list, 
                    organism     ="mmu",
                    nPerm        = 1000,
                    minGSSize    = 120,
                    pvalueCutoff = 0.05,
                    verbose      = FALSE)
```
I got the warning:
```R
Warning message:
In fgsea(pathways = geneSets, stats = geneList, nperm = nPerm, minSize = minGSSize,  :
  There are ties in the preranked stats (11.03% of the list).
The order of those tied genes will be arbitrary, which may produce unexpected results.
```
I think here maybe 11% is quite high? 

But if I prerank it as you mensioned
```R
gene_df = gene_df %>% mutate(rank = rank(bat,  ties.method = "random"))
gene_list = gene_df[[type]]
names(gene_list) = gene_df$ENTREZID

e_kegg = gseKEGG(geneList     = gene_list, 
                    organism     ="mmu",
                    nPerm        = 1000,
                    minGSSize    = 120,
                    pvalueCutoff = 0.05,
                    verbose      = FALSE)
```
，then the gseaKEGG gave error:
```R
 Error in GSEA_internal(geneList = geneList, exponent = exponent, nPerm = nPerm,  : 
  geneList should be a decreasing sorted vector... 
```
Based on this, I assume inside of gseaKEGG, for one sample ,the ranking metrics is expression level.

Could you please kindly give me any hints about this? 

Following is my goal of using clusterProfiler gseaKEGG for analysis,
The normalization method for gene expression is log2 cpm, only one sample. I want to have a look at which pathways are enriched and then select the genes that enriched to one particular pathway to study, this is also the reason why I choose all the genes except for no expression.

Thanks for any information you might provide.

Best,
Cassie

**Comment by necrosnake91** [comment]
Dear Cassie,

It looks like that you are not sorting your results respect to the ranking metric in your data set.
After you insert the new column, called ```rank```, in your data frame, you should use the ```arrange( )``` function of dplyr as follows:

```{r}
gene_df = gene_df %>% mutate(rank = rank(bat,  ties.method = "random")) %>%
arrange(des(rank))
```

This code must sort your data from higher to low values respect to ```rank```
Respect to you other question, are you performing a differential expression analysis? 

Best, 
Rodo

**Comment by JyoRoy21** [comment]
Sorry, this maybe a silly question. After doing the pre-ranking, for the input of gseGO , should the genelist contain the rank values in descending order or the foldchange value?

**Comment by altairwei** [comment]
@JyoRoy21 The `geneList` should contain the rank values, because `DOSE::GSEA_internal` will check it using the following code:

```R
is.sorted <- function(x, decreasing=TRUE) {
    all( sort(x, decreasing=decreasing) == x )
}
```

Otherwise, you will get the same error as @elfore

**Comment by JyoRoy21** [comment]
Yes I get that. But by values you mean the value of the "rank" or the log2foldchange sorted as per the assigned ranks. I tried with just rank values but in that case I lose out the pathways during gseGO analysis which are suppressed due to negative log2FoldChange values (since ranks are all positive)

**Comment by altairwei** [comment]
> Yes I get that. But by values you mean the value of the "rank" or the log2foldchange sorted as per the assigned ranks. I tried with just rank values but in that case I lose out the pathways during gseGO analysis which are suppressed due to negative log2FoldChange values (since ranks are all positive)

Yes, it‘s indeed a problem, because using the rank value will throw away the log fold change. I think a possible way to solve this issue is that pre-ranking `geneList` with ties correction, then sort your `geneList` using rank values in descending order. In this way, you can keep the log fold change and pass `DOSE:::GSEA_internal`'s checking, the warnings from `fgsea` is still there, but you actually corrected the ties.

**Comment by JyoRoy21** [comment]
Yes I agree!
