### ISSUE TITLE
Wikipathways organisms not linked

### ISSUE THREAD

**Issue by aseveritt** [YuLab-SMU/clusterProfiler#632]
Hi all, 

I'm following this [tutorial snippet](https://yulab-smu.top/biomedical-knowledge-mining-book/wikipathways-analysis.html) which has worked fine in the past. However, recently it looks like the wikipathway organisms aren't being linked and is resulting in "No gene can be mapped....". See below. 
<img width="328" alt="clusterProfiler_issue" src="https://github.com/YuLab-SMU/clusterProfiler/assets/13854638/0fb1826a-e9f0-4fa7-a9ed-6587799ff071">

Am I doing something wrong? Or is there a way to provide the GMT files directly to enrichWP? 

Amanda

**Comment by AlexanderPico** [comment]
Short version:
It's fixed! Sorry for the temporary problems.

Long version:
The WikiPathways data archive web site was recently updated and the formatting of the HTML code changed a bit, though the content all stayed the same. This clusterProfiler function depends on formatting of the underlying HTML code to "scrape" information about the GMT files and organisms listed on the web page.  Not ideal, but it works... until it doesn't.  Appreciating the value of WikiPathways content in clusterProfiler, the WikiPathways team immediately updated the format of the HTML for the archive site in order to reestablish compatibility with clusterProfiler functions.

Thanks for reporting this!

**Comment by aseveritt** [comment]
Awesome! Thank you for fixing so quickly!
