### ISSUE TITLE
enrichWP throws error while reading wikipathway GMT file

### ISSUE THREAD

**Issue by rama289** [YuLab-SMU/clusterProfiler#643]
### Describe your issue: I am updating the enrichWP to gseWP (that was my typo)

* [ ] I am using package version 4.10.0 and gseWP(names(genelist), organism = "Homo sapiens")  throws following error: 

* [ ] Error in file(con, "r") : 
  cannot open the connection to 'https://wikipathways-data.wmcloud.org/current/gmt/wikipathways-20231010-gmt-Homo_sapiens.gmt'
In addition: Warning message:
In file(con, "r") :
  cannot open URL 'https://data.wikipathways.org/current/gmt/wikipathways-20231010-gmt-Homo_sapiens.gmt': HTTP status was '404 Not Found')

**Comment by guidohooiveld** [comment]
FYI: Your code is working for me. Maybe it was a temporarily hiccup? Also: are you behind a proxy?

Please note that you aimed to download the GMT file data October 10, 2023, but the current one is from November 10, 2023. Since 'November' is current, the 'October' file is not present anymore in the remote folder named 'current'. Hence the error '404 Not Found'...

Location current files:
https://data.wikipathways.org/current/gmt/

Direct link to current, human file: https://data.wikipathways.org/current/gmt/wikipathways-20231110-gmt-Homo_sapiens.gmt
Let's see whether this will still work after 10 December 2023... :)


```
> library(clusterProfiler)
> data(geneList, package = "DOSE")
> 
> get_wp_organisms()
 [1] "Anopheles gambiae"        "Arabidopsis thaliana"    
 [3] "Bos taurus"               "Caenorhabditis elegans"  
 [5] "Canis familiaris"         "Danio rerio"             
 [7] "Drosophila melanogaster"  "Equus caballus"          
 [9] "Gallus gallus"            "Homo sapiens"            
[11] "Mus musculus"             "Pan troglodytes"         
[13] "Populus trichocarpa"      "Rattus norvegicus"       
[15] "Saccharomyces cerevisiae" "Solanum lycopersicum"    
[17] "Sus scrofa"               "Zea mays"                
> 
> enrichWP(names(geneList), organism = "Homo sapiens")
#
# over-representation test
#
#...@organism    Homo sapiens 
#...@ontology    WikiPathways 
#...@keytype     ENTREZID 
#...@gene        chr [1:12495] "4312" "8318" "10874" "55143" "55388" "991" "6280" "2305" ...
#...pvalues adjusted by 'BH' with cutoff <0.05 
#...303 enriched terms found
'data.frame':   303 obs. of  9 variables:
 $ ID         : chr  "WP5087" "WP3888" "WP3932" "WP481" ...
 $ Description: chr  "Pleural mesothelioma" "VEGFA VEGFR2 signaling" "Focal adhesion PI3K Akt mTOR signaling pathway" "Insulin signaling" ...
 $ GeneRatio  : chr  "399/6491" "393/6491" "280/6491" "155/6491" ...
 $ BgRatio    : chr  "439/8389" "433/8389" "302/8389" "160/8389" ...
 $ pvalue     : num  2.28e-14 6.37e-14 3.83e-13 2.11e-12 5.25e-12 ...
 $ p.adjust   : num  1.57e-11 2.19e-11 8.77e-11 3.62e-10 7.21e-10 ...
 $ qvalue     : num  7.56e-12 1.06e-11 4.23e-11 1.75e-10 3.48e-10 ...
 $ geneID     : chr  "2305/9493/3627/8140/4085/5163/2146/3620/8061/4318/1978/898/6352/51378/1001/83937/6772/6347/8326/4609/6351/10397"| __truncated__ "55872/332/3576/79094/6772/6347/10397/4860/5226/7086/81873/7111/10963/3418/4688/6541/54205/5496/24147/5499/10130"| __truncated__ "3695/1978/51378/3559/3561/54541/3575/1302/6515/2253/3381/3689/3696/6513/6696/2251/1944/5208/2792/2254/1943/5210"| __truncated__ "1978/2888/5871/11184/867/6513/5603/5880/5588/5604/10938/9021/5605/6199/5967/5594/6654/5578/8651/10603/6446/2932"| __truncated__ ...
 $ Count      : int  399 393 280 155 189 310 152 144 112 128 ...
#...Citation
 T Wu, E Hu, S Xu, M Chen, P Guo, Z Dai, T Feng, L Zhou, W Tang, L Zhan, X Fu, S Liu, X Bo, and G Yu.
 clusterProfiler 4.0: A universal enrichment tool for interpreting omics data.
 The Innovation. 2021, 2(3):100141 

> 
> packageVersion("clusterProfiler")
[1] ‘4.10.0’
> 

```

**Comment by youjunpengcsc** [comment]
what should I do, if I am behind a Proxy?

**Comment by guidohooiveld** [comment]
> what should I do, if I am behind a Proxy?

Note that this needs to be taken care of on the level of your `R`-installation, and is not specific for `clusterProfiler`.

Let me start by saying that I don't have any hands-on experience with this (because I am not working from behind a proxy). Yet, you should be able to take care of this by setting the `http_proxy` environment variable. You do this through your `.Rprofile` file, which in essence is a text file (thus having no name, and extension `.Rprofile` [instead of `.txt`]). All information is this file is loaded when you start `R`. Location of this `.Rprofile` file is in your home directory (on my Windows PC this is `C:\Users\hooiv001\documents`).

Add this line:
`Sys.setenv(http_proxy="[username:password]@[proxyAddress]:[port]")`
using your own username, password, and proxy server and port settings, of course!

**Comment by youjunpengcsc** [comment]
Thank you for your kind suggestions which truly helped me a lot!

**Comment by rama289** [comment]
works for me now too, thank you
