### ISSUE TITLE
Cannot library(clusterProfiler)

### ISSUE THREAD

**Issue by HLinChen** [YuLab-SMU/clusterProfiler#660]
### Prerequisites

After I install clusterprofile by BiocManager::install("clusterProfiler"), I want to import the package. But I cannot. The error is:

> library(clusterProfiler)

Error: package or namespace load failed for 'clusterProfiler' in inDL(x, as.logical(local), as.logical(now), ...):
 unable to load shared object 'D:/App/Miniconda/envs/r/lib/R/library/igraph/libs/x64/igraph.dll':
  LoadLibrary failure:  找不到指定的程序。

**Comment by guidohooiveld** [comment]
It looks you are using `R` installed through `miniconda` (thus a container), which I don't have experience with. Yet, based on the error its seems that the package `igraph` isn't installed/available in the environment. So I recommend to install [that](https://cran.r-project.org/web/packages/igraph/index.html), and try again. Or just run R/Bioconductor directly (thus not through a containerized version)...

BTW, I recommend to install `igraph`, available at CRAN, also through `BiocManager` (since then all dependencies are checked). Copy/paste:

```
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("igraph")
```

**Comment by HLinChen** [comment]
Thank you for your help! I have solved this problem by using the newest R and corresponding clusterProfiler package.
