### ISSUE TITLE
bitr报错

### ISSUE THREAD

**Issue by wangtanzhang612** [YuLab-SMU/clusterProfiler#682]
你好！
bitr转ID突然出现报错

    Gene_ID <- bitr(deg$gene,fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Hs.eg.db")
'select()' returned 1:many mapping between keys and columns
Error in bitr(deg$gene, fromType = "SYMBOL", toType = "ENTREZID", OrgDb = "org.Hs.eg.db") : 
  (converted from warning) 6.88% of input gene IDs are fail to map...

**Comment by guidohooiveld** [comment]
I don't fully understand why it is reported as `error`, and not as `warning`, but the issue is that not all the gene symbols you used as input could be converted to entrezid. Maybe you should use `ALIAS` as` fromType`, or, alternatively, it could be that some gene symbols are not valid anymore (input is too old?) and are therefore not 'recognized'.

**Comment by sunyu1010** [comment]
请问解决了吗？

**Comment by guidohooiveld** [comment]
Please use English on this forum!
Yes, since the issue was closed you may assume this it was solved. If you have a question, please open a new issue.
