### ISSUE TITLE
错误于fortify.compareClusterResult(object, showCategory = showCategory, :    找不到对象'gcsize

### ISSUE THREAD

**Issue by Soft283** [YuLab-SMU/clusterProfiler#725]
# my problem
when I run
''dotplot(xx.mus.go, title = paste0("Mouse Gene Ontology (qval < ", qvalueCutoff, "))''
it return ‘错误于fortify.compareClusterResult(object, showCategory = showCategory, :    找不到对象'gcsize’
in my test other function still work well, such as datatable.

**Comment by guidohooiveld** [comment]
This error has been recently reported, and was fixed in dev.

See: https://github.com/YuLab-SMU/enrichplot/issues/291

Bottom line; next to `enrichplot`, you will need to update some other packages as well, since these are dependent on each other.
To update check here: https://github.com/YuLab-SMU/clusterProfiler/issues/715#issuecomment-2298426675
